[package]
name = "druid"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Data-oriented Rust UI design toolkit."
repository = "https://github.com/xi-editor/druid"
categories = ["gui"]
keywords = ["gui", "ui", "toolkit"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[badges]
travis-ci = { repository = "xi-editor/druid" }

[dependencies]
piet-common = "0.0.2"
piet = "0.0.2"
kurbo = "0.2.1"


[dependencies.druid-shell]
path = "druid-shell"
version = "0.2.0"
